#pragma once


enum State {
	UndefinedState,
	Idle,
	JumpSquat,
	GhostJumpSquat,
	GhostJumpWindow,
	Run,
	Walk,
	AirborneNormal,
	JumpSquatLong,
	AirborneLong,
	GhostJumpSquatLong,
	StrongAttack,
	StrongAttack2,
	StrongAttack3,
	StrongFinisher1,
	StrongFinisher2,
	FastFinisher1,
	FastFinisher2,
	FallingAttack,
	HorizontalLauncher,
	VerticalLauncher,
	PropelHigh,
	PropelLong,
	TurnAround,
	Landing,
	LandingFallingAttack,
	HuggingWall,
	WallJumpSquat,
	HuggingWallLongJumpSquat,
	AirborneWallJump,
	ReleasePowerGround,
	JumpSquatSpring,
	IdleTurnAround,
	WallJumpSquatPlummet,
	WallJumpPlummet,
	Death,
	PitFalling,
	HardKnockbackGround,
	HardKnockbackAir,
	Slide,
	SpringJump,
	Dodge
};

enum ConcurrentState {
	UndefinedConcurrentState,
	Free,
	FastAttack,
	FastAttack2,
	FastAttackAir,
	GrabHigh,
	GrabLong,
	ReleasePowerAir,
	SoftKnockbackAir,
	SoftKnockbackGround
};